Recommended prerequisites now has its own page with editable fields
KTH/kursinfo-admin-web pull request #284
Opened 2024-08-16 13:16 UTC by axelbjo

- New admin page for editing recommended prerequisites for a course has been added. The behaviour is the same as for the 'Other information' section.
- Added some simple tests

Note: do not merge this!

2024-08-19 07:56 UTC, karlandindrakryggen approved these changes

2024-08-21 06:34 UTC, amirhossein-haerian approved these changes

2024-08-21 09:23 UTC, allazis requested changes
Good job!

Only one small comment on the language code.

I've tested the publishing functionality and can't see the published text under `Recommended prerequisites` in the course info in REF. Is that expected behaviour at this point? :)

2024-08-21 09:23 UTC, allazis commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
The `(SW)` should be `(SV)` if we're using standard language codes.

2024-08-21 12:03 UTC, axelbjo commented
> Good job!
> 
> Only one small comment on the language code.
> 
> I've tested the publishing functionality and can't see the published text under `Recommended prerequisites` in the course info in REF. Is that expected behaviour at this point? :)

2024-08-21 12:18 UTC, axelbjo commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
That should be expected! The published text under recommended prereuisites is being fetched from Kopps in REF whereas it's being fetched from Om Kursen (kursinfo-api) in the new version (which has not been merged yet)

2024-08-21 12:23 UTC, allazis commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
Super! Only the language code then. 

Well done!

2024-08-21 12:24 UTC, allazis approved these changes

2024-08-21 12:24 UTC, axelbjo commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
> The `(SW)` should be `(SV)` if we're using standard language codes.

I'm wondering if it is supposed to be like that by design? It's something that's being displayed to the user and it changes to (SV) when you change the language on the page to Swedish

2024-08-21 12:28 UTC, axelbjo commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
> Super! Only the language code then.
> 
> Well done!

Thank you! :raised_hands:

2024-08-21 12:39 UTC, allazis commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
> > The `(SW)` should be `(SV)` if we're using standard language codes.
> 
> I'm wondering if it is supposed to be like that by design? It's something that's being displayed to the user and it changes to (SV) when you change the language on the page to Swedish

Interesting! Sounds like it's "planted" from before then. 

However, I would be careful using SW for Swedish as SW stands for Swahili according to the ISO 639 (you know language code widely used when choosing language in dropdowns and such) 😃 This doesn't effect the functionality so its a minor issue. But I would propose a correction of this, maybe as a new issue in Jira? Leave it for now and we can talk about it tomorrow at standup! Sorry about the fussiness over a some what not related matter!

2024-08-21 12:42 UTC, axelbjo commented on i18n/messages.en.js
> +        recommendedPrerequisitesSv: 'Recommended prerequisites (SW)',
> > > The `(SW)` should be `(SV)` if we're using standard language codes.
> > 
> > 
> > I'm wondering if it is supposed to be like that by design? It's something that's being displayed to the user and it changes to (SV) when you change the language on the page to Swedish
> 
> Interesting! Sounds like it's "planted" from before then.
> 
> However, I would be careful using SW for Swedish as SW stands for Swahili according to the ISO 639 (you know language code widely used when choosing language in dropdowns and such) 😃 This doesn't effect the functionality so its a minor issue. But I would propose a correction of this, maybe as a new issue in Jira? Leave it for now and we can talk about it tomorrow at standup! Sorry about the fussiness over a some what not related matter!

That's a good point actually :smile: 
No worries at all, good that you brought it up! We can bring it up tomorrow.

2024-10-04 11:14 UTC, merged